-- =========================================================
-- PetCare360 - Java Advanced Sprint 3
-- Banco de dados para aplicacao Spring Boot
-- Autenticacao por usuario, senha e perfis
-- =========================================================

-- =========================
-- DROP TABLES
-- =========================

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SJ_CARE_RECOMMENDATIONS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SJ_APPOINTMENTS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SJ_PET_MESSAGES CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SJ_PET_VETERINARIANS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SJ_ALERT_HISTORY CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SJ_ALERTS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SJ_SENSOR_DATA CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SJ_DEVICES CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SJ_PETS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SJ_USER_ROLES CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SJ_ROLES CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SJ_USERS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- =========================
-- USERS AND SECURITY
-- =========================

CREATE TABLE SJ_USERS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(120) NOT NULL,
    email VARCHAR2(160) NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    enabled NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_enabled CHECK (enabled IN (0, 1))
);

CREATE TABLE SJ_ROLES (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(40) NOT NULL,
    description VARCHAR2(160),

    CONSTRAINT uk_roles_name UNIQUE (name),
    CONSTRAINT ck_roles_name CHECK (name IN ('ROLE_ADMIN', 'ROLE_CLIENTE', 'ROLE_VETERINARIO'))
);

CREATE TABLE SJ_USER_ROLES (
    user_id NUMBER NOT NULL,
    role_id NUMBER NOT NULL,

    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_users FOREIGN KEY (user_id)
        REFERENCES SJ_USERS(id),
    CONSTRAINT fk_user_roles_roles FOREIGN KEY (role_id)
        REFERENCES SJ_ROLES(id)
);

-- =========================
-- PETS
-- =========================

CREATE TABLE SJ_PETS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    name VARCHAR2(120) NOT NULL,
    age NUMBER(3) NOT NULL,
    weight NUMBER(10,2) NOT NULL,
    breed VARCHAR2(120) NOT NULL,
    species VARCHAR2(40) DEFAULT 'DOG' NOT NULL,
    active NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_pets_users FOREIGN KEY (user_id)
        REFERENCES SJ_USERS(id),
    CONSTRAINT ck_pets_age CHECK (age >= 0),
    CONSTRAINT ck_pets_weight CHECK (weight > 0),
    CONSTRAINT ck_pets_species CHECK (species IN ('DOG', 'CAT', 'OTHER')),
    CONSTRAINT ck_pets_active CHECK (active IN (0, 1))
);

CREATE TABLE SJ_PET_VETERINARIANS (
    pet_id NUMBER NOT NULL,
    veterinarian_id NUMBER NOT NULL,
    assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    active NUMBER(1) DEFAULT 1 NOT NULL,

    CONSTRAINT pk_pet_veterinarians PRIMARY KEY (pet_id, veterinarian_id),
    CONSTRAINT fk_pet_veterinarians_pets FOREIGN KEY (pet_id)
        REFERENCES SJ_PETS(id),
    CONSTRAINT fk_pet_veterinarians_users FOREIGN KEY (veterinarian_id)
        REFERENCES SJ_USERS(id),
    CONSTRAINT ck_pet_veterinarians_active CHECK (active IN (0, 1))
);

-- =========================
-- DEVICES
-- =========================

CREATE TABLE SJ_DEVICES (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_code VARCHAR2(80) NOT NULL,
    pet_id NUMBER NOT NULL,
    status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    battery NUMBER(3) NOT NULL,
    last_seen TIMESTAMP,

    CONSTRAINT uk_devices_code UNIQUE (device_code),
    CONSTRAINT uk_devices_pet UNIQUE (pet_id),
    CONSTRAINT fk_devices_pets FOREIGN KEY (pet_id)
        REFERENCES SJ_PETS(id),
    CONSTRAINT ck_devices_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'MAINTENANCE')),
    CONSTRAINT ck_devices_battery CHECK (battery BETWEEN 0 AND 100)
);

-- =========================
-- SENSOR DATA
-- =========================

CREATE TABLE SJ_SENSOR_DATA (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id NUMBER NOT NULL,
    sensor_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    temperature NUMBER(5,2) NOT NULL,
    heart_rate NUMBER(3) NOT NULL,
    activity_level NUMBER(3) NOT NULL,
    latitude NUMBER(10,6),
    longitude NUMBER(10,6),
    battery NUMBER(3) NOT NULL,
    status VARCHAR2(20) DEFAULT 'NORMAL' NOT NULL,

    CONSTRAINT fk_sensor_data_devices FOREIGN KEY (device_id)
        REFERENCES SJ_DEVICES(id),
    CONSTRAINT ck_sensor_temperature CHECK (temperature BETWEEN 30 AND 45),
    CONSTRAINT ck_sensor_heart_rate CHECK (heart_rate BETWEEN 40 AND 220),
    CONSTRAINT ck_sensor_activity CHECK (activity_level BETWEEN 0 AND 100),
    CONSTRAINT ck_sensor_battery CHECK (battery BETWEEN 0 AND 100),
    CONSTRAINT ck_sensor_status CHECK (status IN ('NORMAL', 'WARNING', 'CRITICAL'))
);

-- =========================
-- ALERTS
-- =========================

CREATE TABLE SJ_ALERTS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id NUMBER NOT NULL,
    type VARCHAR2(40) NOT NULL,
    message VARCHAR2(255) NOT NULL,
    alert_level VARCHAR2(20) NOT NULL,
    status VARCHAR2(20) DEFAULT 'OPEN' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    resolved_at TIMESTAMP,
    resolved_by NUMBER,

    CONSTRAINT fk_alerts_pets FOREIGN KEY (pet_id)
        REFERENCES SJ_PETS(id),
    CONSTRAINT fk_alerts_resolved_by FOREIGN KEY (resolved_by)
        REFERENCES SJ_USERS(id),
    CONSTRAINT ck_alerts_type CHECK (type IN ('ACTIVITY', 'TEMPERATURE', 'HEART_RATE', 'BATTERY')),
    CONSTRAINT ck_alerts_level CHECK (alert_level IN ('INFO', 'WARNING', 'CRITICAL')),
    CONSTRAINT ck_alerts_status CHECK (status IN ('OPEN', 'IN_PROGRESS', 'RESOLVED'))
);

CREATE TABLE SJ_ALERT_HISTORY (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id NUMBER NOT NULL,
    user_id NUMBER NOT NULL,
    previous_status VARCHAR2(20),
    new_status VARCHAR2(20) NOT NULL,
    note VARCHAR2(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_alert_history_alerts FOREIGN KEY (alert_id)
        REFERENCES SJ_ALERTS(id),
    CONSTRAINT fk_alert_history_users FOREIGN KEY (user_id)
        REFERENCES SJ_USERS(id),
    CONSTRAINT ck_alert_history_previous CHECK (
        previous_status IS NULL OR previous_status IN ('OPEN', 'IN_PROGRESS', 'RESOLVED')
    ),
    CONSTRAINT ck_alert_history_new CHECK (new_status IN ('OPEN', 'IN_PROGRESS', 'RESOLVED'))
);

-- =========================
-- MESSAGES
-- =========================

CREATE TABLE SJ_PET_MESSAGES (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id NUMBER NOT NULL,
    sender_id NUMBER NOT NULL,
    receiver_id NUMBER NOT NULL,
    subject VARCHAR2(120) NOT NULL,
    message VARCHAR2(1000) NOT NULL,
    status VARCHAR2(20) DEFAULT 'SENT' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    read_at TIMESTAMP,

    CONSTRAINT fk_pet_messages_pets FOREIGN KEY (pet_id)
        REFERENCES SJ_PETS(id),
    CONSTRAINT fk_pet_messages_sender FOREIGN KEY (sender_id)
        REFERENCES SJ_USERS(id),
    CONSTRAINT fk_pet_messages_receiver FOREIGN KEY (receiver_id)
        REFERENCES SJ_USERS(id),
    CONSTRAINT ck_pet_messages_status CHECK (status IN ('SENT', 'READ', 'ANSWERED')),
    CONSTRAINT ck_pet_messages_users CHECK (sender_id <> receiver_id)
);

CREATE TABLE SJ_APPOINTMENTS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id NUMBER NOT NULL,
    tutor_id NUMBER NOT NULL,
    veterinarian_id NUMBER NOT NULL,
    scheduled_at TIMESTAMP NOT NULL,
    reason VARCHAR2(255) NOT NULL,
    status VARCHAR2(20) DEFAULT 'REQUESTED' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_appointments_pets FOREIGN KEY (pet_id)
        REFERENCES SJ_PETS(id),
    CONSTRAINT fk_appointments_tutor FOREIGN KEY (tutor_id)
        REFERENCES SJ_USERS(id),
    CONSTRAINT fk_appointments_vet FOREIGN KEY (veterinarian_id)
        REFERENCES SJ_USERS(id),
    CONSTRAINT ck_appointments_status CHECK (status IN ('REQUESTED', 'CONFIRMED', 'CANCELED', 'DONE')),
    CONSTRAINT ck_appointments_users CHECK (tutor_id <> veterinarian_id)
);

CREATE TABLE SJ_CARE_RECOMMENDATIONS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id NUMBER NOT NULL,
    veterinarian_id NUMBER NOT NULL,
    tutor_id NUMBER NOT NULL,
    title VARCHAR2(120) NOT NULL,
    instructions VARCHAR2(1000) NOT NULL,
    priority VARCHAR2(20) DEFAULT 'NORMAL' NOT NULL,
    status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,

    CONSTRAINT fk_care_recommendations_pets FOREIGN KEY (pet_id)
        REFERENCES SJ_PETS(id),
    CONSTRAINT fk_care_recommendations_vet FOREIGN KEY (veterinarian_id)
        REFERENCES SJ_USERS(id),
    CONSTRAINT fk_care_recommendations_tutor FOREIGN KEY (tutor_id)
        REFERENCES SJ_USERS(id),
    CONSTRAINT ck_care_recommendations_priority CHECK (priority IN ('LOW', 'NORMAL', 'HIGH')),
    CONSTRAINT ck_care_recommendations_status CHECK (status IN ('ACTIVE', 'COMPLETED', 'CANCELED')),
    CONSTRAINT ck_care_recommendations_users CHECK (tutor_id <> veterinarian_id)
);

-- =========================
-- INDEXES
-- =========================

CREATE INDEX idx_pets_user_id ON SJ_PETS(user_id);
CREATE INDEX idx_user_roles_role_id ON SJ_USER_ROLES(role_id);
CREATE INDEX idx_pet_veterinarians_vet ON SJ_PET_VETERINARIANS(veterinarian_id);
CREATE INDEX idx_sensor_data_device_id ON SJ_SENSOR_DATA(device_id);
CREATE INDEX idx_sensor_data_timestamp ON SJ_SENSOR_DATA(sensor_timestamp);
CREATE INDEX idx_alerts_pet_id ON SJ_ALERTS(pet_id);
CREATE INDEX idx_alerts_status ON SJ_ALERTS(status);
CREATE INDEX idx_alerts_created_at ON SJ_ALERTS(created_at);
CREATE INDEX idx_alert_history_alert_id ON SJ_ALERT_HISTORY(alert_id);
CREATE INDEX idx_pet_messages_pet_id ON SJ_PET_MESSAGES(pet_id);
CREATE INDEX idx_pet_messages_receiver ON SJ_PET_MESSAGES(receiver_id);
CREATE INDEX idx_appointments_tutor ON SJ_APPOINTMENTS(tutor_id);
CREATE INDEX idx_appointments_vet ON SJ_APPOINTMENTS(veterinarian_id);
CREATE INDEX idx_appointments_status ON SJ_APPOINTMENTS(status);
CREATE INDEX idx_care_recommendations_pet ON SJ_CARE_RECOMMENDATIONS(pet_id);
CREATE INDEX idx_care_recommendations_tutor ON SJ_CARE_RECOMMENDATIONS(tutor_id);
CREATE INDEX idx_care_recommendations_vet ON SJ_CARE_RECOMMENDATIONS(veterinarian_id);
